version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Canada/Pacific
    reviewers:
      - cloudshiftchris
    commit-message:
      prefix: chore
    groups:
      workflow-actions:
        patterns:
          - '*'
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      time: '06:00'
      timezone: Canada/Pacific
    reviewers:
      - cloudshiftchris
    commit-message:
      prefix: chore
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      gradle-patch-updates:
        update-types:
          - patch
      gradle-minor-updates:
        exclude-patterns:
          - org.jetbrains.kotlin*
        update-types:
          - minor
