# Reference: https://docs.gradle.org/current/userguide/platforms.html

[versions]
kotlin = "1.9.25"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version = "0.20.1" }

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.1" }

##### Testing libraries

kotest-bom = { module = "io.kotest:kotest-bom", version = "5.9.1" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
