
name: 'Build Kontour'
on:
  pull_request: {}
permissions:
  contents: 'write'
env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: 'false'
  ORG_GRADLE_PROJECT_signingInMemoryKey: '${{ secrets.SIGNING_KEY }}'
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: '${{ secrets.SIGNING_PASSWORD }}'
  ORG_GRADLE_PROJECT_mavenCentralUsername: '${{ secrets.SONATYPEUSERNAME }}'
  ORG_GRADLE_PROJECT_mavenCentralPassword: '${{ secrets.SONATYPEPASSWORD }}'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    # https://github.com/hmarr/debug-action
    - uses: 'hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820' # v3.0.0

    # https://github.com/zgosalvez/github-actions-ensure-sha-pinned-actions
    - uses: 'zgosalvez/github-actions-ensure-sha-pinned-actions@ba37328d4ea95eaf8b3bd6c6cef308f709a5f2ec' # v3.0.3

    # https://github.com/actions/checkout
    - name: 'checkout'
      uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # v4.1.1

    # https://github.com/actions/setup-java
    - name: 'Set up JDK'
      uses: 'actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8' # v4.1.0
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: 'true'

    # https://github.com/gradle/wrapper-validation-action
    - name: 'Validate Gradle Wrapper'
      uses: 'gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2' # v2.1.1

    # https://github.com/gradle/actions/tree/main/setup-gradle
    - name: 'Set up Gradle'
      uses: 'gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5' # v3.1.0
      with:
        gradle-version: 'wrapper'
        gradle-home-cache-includes: |-
          jdks
          caches
          notifications
        gradle-home-cache-cleanup: 'true'
        dependency-graph: 'generate-and-submit'

    - name: 'Build'
      run: './gradlew build --info --scan --stacktrace'

    - name: 'Publish'
      run: './gradlew publishAllPublicationsToMavenCentralRepository --info --stacktrace --no-configuration-cache'
